services:
  bot:
    build:
      context: .
      network: host
    container_name: gd_leaderboard_bot
    network_mode: "host"
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
